# Final no-anchor training-health confirmation（6/20）

这是进入正式 Stage 5 前的最后一次独立健康确认。固定 `policy_max_norm=5`、`retry=3`，从全新 policy/optimizer/scheduler 开始；不恢复旧 Step 12 或 clipping A/B 训练状态，不使用短期 Reward/IC 选择参数，也不会自动创建正式训练 run。

### 第 0 格：检查最终候选配置与安全开关

这一格只构造配置并显示 F/D/E/L、输入文件、32-batch 预算和健康门槛，不加载真实数据，通常几秒完成。首次运行保持 `RUN_MODE='new'`；确认后把 `RUN_REAL_FINAL_HEALTH=False` 改成 `True`。

In [2]:
import json, math, sys, torch
from dataclasses import asdict, replace
from pathlib import Path
from time import perf_counter
import numpy as np
import pandas as pd

root = next(p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents) if (p / 'factor_gfn').is_dir())
if str(root) not in sys.path: sys.path.insert(0, str(root))
from factor_gfn.gfn import (ExhaustiveRegistry, GFNTrainer, LogZInitializationHealthConfig, NoAnchorCalibrationConfig, RealRewardDataPaths, RealRewardProvider, TrainingConfig, build_formal_stage5_no_anchor_6_20_config, build_log_z_initialization_health, build_real_reward_data_context)
from factor_gfn.gfn.diagnostic_support import PhaseTrackingRewardProvider, configure_registry_once, progress_heartbeat, run_training_with_progress

RUN_REAL_FINAL_HEALTH = False
RUN_MODE = 'new'  # 中断后改为 'resume'，然后从第0格顺序运行
DEVICE = 'cuda:0'
LOGICAL_BATCHES = 32
SOURCE_DIAGNOSTIC_ROOT = root / 'runs' / 'complexity_diagnostic_6_20' / 'manual_diagnostic_6_20_seed42'
SOURCE_REGISTRY = SOURCE_DIAGNOSTIC_ROOT / 'exhaustive_registry.sqlite3'
TARGETED_ARTIFACT = root / 'runs' / 'targeted_calibration_6_20' / 'targeted_logz_n17_n18_seed42' / 'targeted_log_z_engineering_initialization.json'
RUN_ROOT = root / 'runs' / 'final_health_confirmation_6_20' / 'final_health_seed42'
LATEST_CHECKPOINT = RUN_ROOT / 'latest_no_anchor.pt'
training = TrainingConfig(batch_size=8, learning_rate=1e-4, log_z_learning_rate=1e-2, max_steps=LOGICAL_BATCHES + 2, model_gradient_clip_norm=5.0, log_z_gradient_clip_norm=5.0, seed=42)
base_config = build_formal_stage5_no_anchor_6_20_config(training=training)
config = replace(base_config, complexity=replace(base_config.complexity, exact_node_retry_budget=3), calibration=NoAnchorCalibrationConfig(enabled=True, target_node_counts=(17, 18)))
health_config = LogZInitializationHealthConfig()
strata = config.resolved_strata()
print({'enabled': RUN_REAL_FINAL_HEALTH, 'run_mode': RUN_MODE, 'device': DEVICE, 'run_root': str(RUN_ROOT), 'logical_batches': LOGICAL_BATCHES, 'F': strata.feasible_node_counts, 'D': strata.discovery_node_counts, 'E': strata.exact_normalizer_node_counts, 'L': strata.learned_normalizer_node_counts, 'policy_max_norm': 5.0, 'retry_budget': 3, 'batch_size': 8, 'policy_lr': 1e-4, 'logZ_lr': 1e-2, 'logZ_max_norm': 5.0, 'health_config': asdict(health_config), 'config_fingerprint': config.fingerprint()}, flush=True)
print('预计32个batch约30–40分钟；末尾确定性恢复再约2–4分钟。每个batch逐项输出，内部每20秒heartbeat。', flush=True)

{'enabled': True, 'run_mode': 'new', 'device': 'cuda:0', 'run_root': 'D:\\实习\\Gflownet因子挖掘\\runs\\final_health_confirmation_6_20\\final_health_seed42', 'logical_batches': 32, 'F': (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20), 'D': (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20), 'E': (1, 2), 'L': (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20), 'policy_max_norm': 5.0, 'retry_budget': 3, 'batch_size': 8, 'policy_lr': 0.0001, 'logZ_lr': 0.01, 'logZ_max_norm': 5.0, 'health_config': {'minimum_valid_trajectories_per_N': 7, 'minimum_successful_gradient_exposures_per_N': 7, 'early_exposure_count': 3, 'late_exposure_count': 3, 'initial_abs_delta_mean_review_threshold': 5.0, 'late_abs_delta_mean_review_threshold': 2.5, 'log_z_net_change_review_threshold': 0.75, 'directional_drift_fraction_threshold': 0.8, 'minimum_log_z_step_for_direction': 0.0001}, 'config_fingerprint': 'a56cb11bf4da0b782cdfdb9570b07c6705cffa1272730c23e69261aef56702ab'}
预计32个batch约30–40分钟；末尾确定性恢复再约2–4分钟。每个batch逐项输出，内部每20秒heartbeat。

### 第 1 格：建立或恢复独立最终 health run

这一格加载真实 training-only 数据、检查行业中性化，重新完成只读 registry 等价证明。`new` 模式创建全新 Trainer，导入 historical median 后只用工程 artifact 覆盖 N=17/18；`resume` 只恢复本 run 的新 schema checkpoint。不会重新执行 exhaustive Reward 或 calibration。通常数分钟，超过20秒持续输出心跳。

In [3]:
if not RUN_REAL_FINAL_HEALTH: raise RuntimeError('安全停止：确认第0格后，将 RUN_REAL_FINAL_HEALTH=True')
if RUN_MODE not in {'new','resume'}: raise ValueError("RUN_MODE只能是'new'或'resume'")
if not DEVICE.startswith('cuda:') or not torch.cuda.is_available(): raise RuntimeError('最终health必须显式使用CUDA，不回落CPU')
for required in (SOURCE_REGISTRY, TARGETED_ARTIFACT, SOURCE_DIAGNOSTIC_ROOT / 'diagnostic_summary.json', SOURCE_DIAGNOSTIC_ROOT / 'diagnostic_context.json'):
    if not required.is_file(): raise FileNotFoundError(required)
device=torch.device(DEVICE); torch.cuda.set_device(device); torch.cuda.reset_peak_memory_stats(device)
if RUN_MODE=='new': RUN_ROOT.mkdir(parents=True, exist_ok=False)
elif not RUN_ROOT.is_dir(): raise FileNotFoundError('resume要求既有同名最终health目录')
print('[provider] loading training-only context; heartbeat every 20s', flush=True)
with progress_heartbeat('final health provider load', interval_seconds=20.0):
    context=build_real_reward_data_context(paths=RealRewardDataPaths())
    base_provider=RealRewardProvider(context, config.reward)
    provider=PhaseTrackingRewardProvider(base_provider, audit_path=RUN_ROOT/'reward_phase_audit.jsonl')
manifest=provider.manifest()
assert manifest['data_scope']=='training_only' and manifest['validation_oos_loaded'] is False
assert manifest['industry_neutralization']['enabled'] and base_provider.reward_config.candidate_industry_neutralization
registry=ExhaustiveRegistry(SOURCE_REGISTRY, read_only=True)
trainer=GFNTrainer(config, provider, device=device)
with progress_heartbeat('final health registry equivalence proof', interval_seconds=20.0): configure_registry_once(trainer, registry)
if RUN_MODE=='resume':
    if not LATEST_CHECKPOINT.is_file(): raise FileNotFoundError(LATEST_CHECKPOINT)
    trainer.load_checkpoint(LATEST_CHECKPOINT)
    historical=trainer.historical_log_z_initialization; targeted=trainer.targeted_log_z_initialization
    initial_manifest=json.loads((RUN_ROOT/'initialization_manifest.json').read_text(encoding='utf-8'))
    initial_log_z_by_N={int(k):float(v) for k,v in initial_manifest['initial_log_z_by_N'].items()}
    print(f'[resume] logical={trainer.step}, successful={trainer.optimizer_step}', flush=True)
else:
    with progress_heartbeat('final health historical initialization proof', interval_seconds=20.0): historical=trainer.initialize_verified_historical_log_z(SOURCE_DIAGNOSTIC_ROOT)
    targeted=trainer.initialize_verified_targeted_log_z(TARGETED_ARTIFACT)
    assert targeted.initialization_status=='high_variance_engineering_estimate' and targeted.strict_stability_check=='failed'
    initial_log_z_by_N={**{n:float(trainer.tb_loss.exact_tb_log_z_by_node_count[n-1]) for n in trainer.resolved_exhaustive_node_counts}, **{n:float(trainer.tb_loss.log_z_by_node_count[n-1]) for n in trainer.resolved_learned_node_counts}}
    initial_manifest={'schema':'factor_gfn.final_health_initialization.v1','config_fingerprint':config.fingerprint(),'provider_fingerprint':provider.fingerprint(),'historical_provenance_fingerprint':historical.provenance_fingerprint,'targeted_provenance_fingerprint':targeted.provenance_fingerprint,'targeted_status':targeted.initialization_status,'strict_stability_check':targeted.strict_stability_check,'initial_log_z_by_N':initial_log_z_by_N}
    (RUN_ROOT/'initialization_manifest.json').write_text(json.dumps(initial_manifest,ensure_ascii=False,indent=2),encoding='utf-8')
    trainer.save_checkpoint(LATEST_CHECKPOINT)
if targeted is None or historical is None: raise RuntimeError('初始化provenance不完整')
assert set(initial_log_z_by_N)==set(trainer.resolved_feasible_node_counts)
print('[initialization] exact N=1/2 and learned N=3..20 ready; N17/N18=',{n:initial_log_z_by_N[n] for n in (17,18)},flush=True)
print('[initialization] no old model/optimizer/scheduler state was imported in new mode',flush=True)

[provider] loading training-only context; heartbeat every 20s

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[registry-proof] verified_once={1: 6, 2: 636}
[initialization] exact N=1/2 and learned N=3..20 ready; N17/N18= {17: 46.30188751220703, 18: 46.4272575378418}
[initialization] no old model/optimizer/scheduler state was imported in new mode

### 第 2 格：运行32个 logical batch

这是主要长计算格。每个 batch 开始和结束都打印 logical/successful/skipped、loss、TB RMS、retry、耗时和 ETA；batch 内每20秒 heartbeat；每个 batch 原子保存 checkpoint。中断后设 `RUN_MODE='resume'`，重启内核并从第0格顺序运行。预计约30–40分钟。

In [4]:
training_path=RUN_ROOT/'training_health.jsonl'; trajectory_path=RUN_ROOT/'trajectory_tb_diagnostics.jsonl'
remaining=max(0,LOGICAL_BATCHES-trainer.step)
if remaining:
    print(f'[training] remaining logical batches={remaining}; current successful={trainer.optimizer_step}',flush=True)
    with provider.phase('final_health_discovery'):
        run_training_with_progress(trainer,logical_batches=remaining,checkpoint_path=LATEST_CHECKPOINT,checkpoint_every=1,training_audit_path=training_path,trajectory_audit_path=trajectory_path)
else: print('[training] 32-batch budget already complete in checkpoint',flush=True)
print(f'[training] complete logical={trainer.step}, successful={trainer.optimizer_step}, skipped={trainer.step-trainer.optimizer_step}',flush=True)

[training] remaining logical batches=32; current successful=0
[training] starting invocation_batch=1/32, logical_batch=1, trainer_step=0, successful_updates=0
[training logical_batch=1] still running; elapsed=20.0s
[training logical_batch=1] still running; elapsed=40.1s
[training logical_batch=1] still running; elapsed=60.2s
[training] invocation_batch=1/32, logical_batch=1, successful_updates=1, skipped=False, loss=6.496564202875464, tb_rms=2.5488358524776493, requested={1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 1, 11: 0, 12: 0, 13: 0, 14: 1, 15: 1, 16: 1, 17: 0, 18: 0, 19: 1, 20: 1}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0}, elapsed=75.8s, eta=2348.4s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=2/32, logical_batch=2, trainer_step=1, successful_updates=1
[training logical_batch=2] still running; elapsed=20.0s
[training logical_batch=2] still running; elapsed=40.2s
[training logical_batch=2] still running; elapsed=60.2s
[training] invocation_batch=2/32, logical_batch=2, successful_updates=1, skipped=True, loss=None, tb_rms=None, requested={1: 0, 2: 1, 3: 1, 4: 0, 5: 1, 6: 1, 7: 1, 8: 0, 9: 0, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 1, 18: 1, 19: 1, 20: 1}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=138.1s, eta=2070.8s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=3/32, logical_batch=3, trainer_step=2, successful_updates=1
[training logical_batch=3] still running; elapsed=20.0s
[training] invocation_batch=3/32, logical_batch=3, successful_updates=2, skipped=False, loss=5.932803665627668, tb_rms=2.4357347280908215, requested={1: 1, 2: 1, 3: 1, 4: 2, 5: 1, 6: 1, 7: 1, 8: 1, 9: 2, 10: 1, 11: 1, 12: 2, 13: 1, 14: 1, 15: 2, 16: 1, 17: 1, 18: 1, 19: 1, 20: 1}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=172.7s, eta=1669.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=4/32, logical_batch=4, trainer_step=3, successful_updates=2
[training logical_batch=4] still running; elapsed=20.0s
[training logical_batch=4] still running; elapsed=40.1s
[training] invocation_batch=4/32, logical_batch=4, successful_updates=3, skipped=False, loss=43.67802882697579, tb_rms=6.6089355290376215, requested={1: 2, 2: 2, 3: 2, 4: 2, 5: 1, 6: 2, 7: 1, 8: 1, 9: 2, 10: 1, 11: 2, 12: 2, 13: 2, 14: 1, 15: 2, 16: 1, 17: 2, 18: 1, 19: 2, 20: 1}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=228.2s, eta=1597.4s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=5/32, logical_batch=5, trainer_step=4, successful_updates=3
[training logical_batch=5] still running; elapsed=20.0s
[training logical_batch=5] still running; elapsed=40.0s
[training] invocation_batch=5/32, logical_batch=5, successful_updates=4, skipped=False, loss=34.1911425723299, tb_rms=5.84731926375924, requested={1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 2, 12: 2, 13: 2, 14: 2, 15: 2, 16: 2, 17: 2, 18: 2, 19: 2, 20: 2}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=281.9s, eta=1522.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=6/32, logical_batch=6, trainer_step=5, successful_updates=4
[training logical_batch=6] still running; elapsed=20.0s
[training] invocation_batch=6/32, logical_batch=6, successful_updates=5, skipped=False, loss=9.499501193118801, tb_rms=3.0821260832611634, requested={1: 3, 2: 2, 3: 3, 4: 2, 5: 3, 6: 3, 7: 2, 8: 2, 9: 2, 10: 3, 11: 3, 12: 2, 13: 2, 14: 3, 15: 2, 16: 2, 17: 2, 18: 2, 19: 2, 20: 3}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=317.3s, eta=1375.1s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=7/32, logical_batch=7, trainer_step=6, successful_updates=5
[training logical_batch=7] still running; elapsed=20.0s
[training logical_batch=7] still running; elapsed=40.1s
[training logical_batch=7] still running; elapsed=60.2s
[training logical_batch=7] still running; elapsed=80.4s
[training logical_batch=7] still running; elapsed=100.5s
[training] invocation_batch=7/32, logical_batch=7, successful_updates=6, skipped=False, loss=19.18699984901965, tb_rms=4.380296776363406, requested={1: 3, 2: 3, 3: 3, 4: 2, 5: 3, 6: 3, 7: 3, 8: 3, 9: 2, 10: 3, 11: 3, 12: 2, 13: 3, 14: 3, 15: 3, 16: 3, 17: 3, 18: 3, 19: 2, 20: 3}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=434.8s, eta=1552.9s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=8/32, logical_batch=8, trainer_step=7, successful_updates=6
[training logical_batch=8] still running; elapsed=20.0s
[training] invocation_batch=8/32, logical_batch=8, successful_updates=7, skipped=False, loss=4.553615165243495, tb_rms=2.133920140315353, requested={1: 4, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 4, 10: 3, 11: 4, 12: 3, 13: 3, 14: 3, 15: 4, 16: 3, 17: 3, 18: 3, 19: 3, 20: 3}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=467.5s, eta=1402.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=9/32, logical_batch=9, trainer_step=8, successful_updates=7
[training logical_batch=9] still running; elapsed=20.0s
[training logical_batch=9] still running; elapsed=40.0s
[training] invocation_batch=9/32, logical_batch=9, successful_updates=8, skipped=False, loss=13.081762853056485, tb_rms=3.616871970785873, requested={1: 4, 2: 3, 3: 3, 4: 3, 5: 4, 6: 4, 7: 4, 8: 3, 9: 4, 10: 3, 11: 4, 12: 4, 13: 4, 14: 3, 15: 4, 16: 4, 17: 4, 18: 4, 19: 3, 20: 3}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=510.4s, eta=1304.4s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=10/32, logical_batch=10, trainer_step=9, successful_updates=8
[training logical_batch=10] still running; elapsed=20.0s
[training logical_batch=10] still running; elapsed=40.1s
[training logical_batch=10] still running; elapsed=60.1s
[training] invocation_batch=10/32, logical_batch=10, successful_updates=9, skipped=False, loss=16.152029274912966, tb_rms=4.018958730182852, requested={1: 4, 2: 4, 3: 4, 4: 4, 5: 4, 6: 4, 7: 4, 8: 4, 9: 4, 10: 4, 11: 4, 12: 4, 13: 4, 14: 4, 15: 4, 16: 4, 17: 4, 18: 4, 19: 4, 20: 4}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=572.7s, eta=1259.8s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=11/32, logical_batch=11, trainer_step=10, successful_updates=9
[training logical_batch=11] still running; elapsed=20.0s
[training] invocation_batch=11/32, logical_batch=11, successful_updates=10, skipped=False, loss=17.7742705025776, tb_rms=4.215954281367102, requested={1: 5, 2: 5, 3: 5, 4: 4, 5: 4, 6: 4, 7: 4, 8: 4, 9: 4, 10: 5, 11: 4, 12: 5, 13: 5, 14: 5, 15: 5, 16: 4, 17: 4, 18: 4, 19: 4, 20: 4}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=608.8s, eta=1162.2s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=12/32, logical_batch=12, trainer_step=11, successful_updates=10
[training logical_batch=12] still running; elapsed=20.0s
[training logical_batch=12] still running; elapsed=40.1s
[training] invocation_batch=12/32, logical_batch=12, successful_updates=11, skipped=False, loss=47.832495914797406, tb_rms=6.916104099476627, requested={1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 4, 7: 5, 8: 4, 9: 5, 10: 5, 11: 5, 12: 5, 13: 5, 14: 5, 15: 5, 16: 5, 17: 5, 18: 4, 19: 5, 20: 4}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=658.4s, eta=1097.3s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=13/32, logical_batch=13, trainer_step=12, successful_updates=11
[training logical_batch=13] still running; elapsed=20.0s
[training logical_batch=13] still running; elapsed=40.1s
[training logical_batch=13] still running; elapsed=60.1s
[training logical_batch=13] still running; elapsed=80.2s
[training] invocation_batch=13/32, logical_batch=13, successful_updates=12, skipped=False, loss=9.743655189489827, tb_rms=3.1214828510645107, requested={1: 6, 2: 6, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 6, 11: 5, 12: 5, 13: 5, 14: 5, 15: 6, 16: 5, 17: 5, 18: 5, 19: 5, 20: 5}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=751.8s, eta=1098.7s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=14/32, logical_batch=14, trainer_step=13, successful_updates=12
[training logical_batch=14] still running; elapsed=20.1s
[training] invocation_batch=14/32, logical_batch=14, successful_updates=13, skipped=False, loss=6.3139590443007325, tb_rms=2.5127592491722583, requested={1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 6, 10: 6, 11: 5, 12: 6, 13: 6, 14: 6, 15: 6, 16: 5, 17: 5, 18: 5, 19: 5, 20: 5}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=774.2s, eta=995.4s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=15/32, logical_batch=15, trainer_step=14, successful_updates=13
[training logical_batch=15] still running; elapsed=20.0s
[training logical_batch=15] still running; elapsed=40.0s
[training logical_batch=15] still running; elapsed=60.1s
[training] invocation_batch=15/32, logical_batch=15, successful_updates=14, skipped=False, loss=48.292438345828536, tb_rms=6.949276102287816, requested={1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 6, 11: 6, 12: 6, 13: 6, 14: 6, 15: 6, 16: 6, 17: 6, 18: 6, 19: 6, 20: 6}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=836.2s, eta=947.7s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=16/32, logical_batch=16, trainer_step=15, successful_updates=14
[training logical_batch=16] still running; elapsed=20.0s
[training logical_batch=16] still running; elapsed=40.0s
[training logical_batch=16] still running; elapsed=60.1s
[training] invocation_batch=16/32, logical_batch=16, successful_updates=15, skipped=False, loss=42.15202843588707, tb_rms=6.492459351885622, requested={1: 7, 2: 6, 3: 6, 4: 7, 5: 6, 6: 7, 7: 6, 8: 7, 9: 7, 10: 7, 11: 6, 12: 7, 13: 6, 14: 6, 15: 6, 16: 6, 17: 6, 18: 6, 19: 6, 20: 7}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=914.5s, eta=914.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=17/32, logical_batch=17, trainer_step=16, successful_updates=15
[training logical_batch=17] still running; elapsed=20.0s
[training logical_batch=17] still running; elapsed=40.1s
[training logical_batch=17] still running; elapsed=60.2s
[training] invocation_batch=17/32, logical_batch=17, successful_updates=16, skipped=False, loss=29.71331584698966, tb_rms=5.450992189224789, requested={1: 7, 2: 7, 3: 6, 4: 7, 5: 6, 6: 7, 7: 7, 8: 7, 9: 7, 10: 7, 11: 7, 12: 7, 13: 7, 14: 7, 15: 7, 16: 6, 17: 6, 18: 7, 19: 7, 20: 7}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=987.8s, eta=871.6s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=18/32, logical_batch=18, trainer_step=17, successful_updates=16
[training logical_batch=18] still running; elapsed=20.0s
[training] invocation_batch=18/32, logical_batch=18, successful_updates=17, skipped=False, loss=38.25274638266654, tb_rms=6.184880466319987, requested={1: 7, 2: 8, 3: 7, 4: 7, 5: 7, 6: 8, 7: 7, 8: 7, 9: 7, 10: 7, 11: 7, 12: 7, 13: 7, 14: 8, 15: 7, 16: 8, 17: 7, 18: 7, 19: 7, 20: 7}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1025.4s, eta=797.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=19/32, logical_batch=19, trainer_step=18, successful_updates=17
[training logical_batch=19] still running; elapsed=20.0s
[training logical_batch=19] still running; elapsed=40.1s
[training] invocation_batch=19/32, logical_batch=19, successful_updates=18, skipped=False, loss=14.205955788105072, tb_rms=3.769078904467917, requested={1: 8, 2: 8, 3: 7, 4: 7, 5: 7, 6: 8, 7: 7, 8: 8, 9: 7, 10: 8, 11: 7, 12: 8, 13: 8, 14: 8, 15: 8, 16: 8, 17: 8, 18: 7, 19: 8, 20: 7}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1084.2s, eta=741.8s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=20/32, logical_batch=20, trainer_step=19, successful_updates=18
[training logical_batch=20] still running; elapsed=20.0s
[training logical_batch=20] still running; elapsed=40.1s
[training logical_batch=20] still running; elapsed=60.1s
[training] invocation_batch=20/32, logical_batch=20, successful_updates=19, skipped=False, loss=57.41725572538088, tb_rms=7.577417483904452, requested={1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 8, 8: 8, 9: 8, 10: 8, 11: 8, 12: 8, 13: 8, 14: 8, 15: 8, 16: 8, 17: 8, 18: 8, 19: 8, 20: 8}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1145.8s, eta=687.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=21/32, logical_batch=21, trainer_step=20, successful_updates=19
[training logical_batch=21] still running; elapsed=20.0s
[training logical_batch=21] still running; elapsed=40.1s
[training] invocation_batch=21/32, logical_batch=21, successful_updates=20, skipped=False, loss=42.01875252022235, tb_rms=6.4821873252955555, requested={1: 8, 2: 8, 3: 9, 4: 8, 5: 8, 6: 8, 7: 9, 8: 8, 9: 9, 10: 9, 11: 8, 12: 9, 13: 9, 14: 8, 15: 9, 16: 9, 17: 8, 18: 8, 19: 8, 20: 8}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1186.2s, eta=621.3s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=22/32, logical_batch=22, trainer_step=21, successful_updates=20
[training logical_batch=22] still running; elapsed=20.0s
[training logical_batch=22] still running; elapsed=40.1s
[training logical_batch=22] still running; elapsed=60.2s
[training logical_batch=22] still running; elapsed=80.2s
[training] invocation_batch=22/32, logical_batch=22, successful_updates=21, skipped=False, loss=25.31718227656629, tb_rms=5.0316182562438385, requested={1: 8, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 9, 8: 9, 9: 9, 10: 9, 11: 9, 12: 9, 13: 9, 14: 9, 15: 9, 16: 9, 17: 8, 18: 8, 19: 9, 20: 9}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1277.2s, eta=580.5s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=23/32, logical_batch=23, trainer_step=22, successful_updates=21
[training logical_batch=23] still running; elapsed=20.0s
[training logical_batch=23] still running; elapsed=40.1s
[training] invocation_batch=23/32, logical_batch=23, successful_updates=22, skipped=False, loss=5.083029720703237, tb_rms=2.254557544331756, requested={1: 10, 2: 10, 3: 9, 4: 9, 5: 9, 6: 9, 7: 9, 8: 10, 9: 9, 10: 9, 11: 9, 12: 10, 13: 9, 14: 9, 15: 9, 16: 9, 17: 9, 18: 9, 19: 9, 20: 9}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1321.6s, eta=517.1s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=24/32, logical_batch=24, trainer_step=23, successful_updates=22
[training logical_batch=24] still running; elapsed=20.0s
[training logical_batch=24] still running; elapsed=40.0s
[training logical_batch=24] still running; elapsed=60.0s
[training logical_batch=24] still running; elapsed=80.1s
[training] invocation_batch=24/32, logical_batch=24, successful_updates=23, skipped=False, loss=31.35558447684351, tb_rms=5.599605742982582, requested={1: 10, 2: 10, 3: 10, 4: 10, 5: 9, 6: 9, 7: 10, 8: 10, 9: 9, 10: 9, 11: 10, 12: 10, 13: 10, 14: 9, 15: 10, 16: 9, 17: 10, 18: 9, 19: 9, 20: 10}, retries={1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 1, 18: 0, 19: 0, 20: 0}, elapsed=1413.1s, eta=471.0s
[training] checkpoint=D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42\latest_no_anchor.pt
[training] starting invocation_batch=25/32, logical_batch=25, trainer_step=24, successful_updates=23
[training logical_batch=25] still running; elapsed=20.0s
[training logical_batch=25] still running; elapsed=40.0s

### 第 3 格：生成 per-N 最终健康报告

这一格不再训练，通常几秒完成。它按 logical batch 去重审计，分别保留每个 N 的 initialization/pre-update、early、late TB delta，以及 initial/current/net-change logZ、valid和successful exposure；同时汇总梯度、裁剪、实际更新、retry、吞吐和显存。证据不足或异常只报告，不自动重置logZ或修改参数。

In [5]:
raw_training=[json.loads(x) for x in training_path.read_text(encoding='utf-8').splitlines() if x.strip()]
training_rows=list({int(r['logical_batch']):r for r in raw_training}.values()); training_rows.sort(key=lambda r:int(r['logical_batch']))
raw_trajectory=[json.loads(x) for x in trajectory_path.read_text(encoding='utf-8').splitlines() if x.strip()]
trajectory_rows=list({(int(r['logical_batch']),int(r['candidate_index_in_batch'])):r for r in raw_trajectory}.values()); trajectory_rows.sort(key=lambda r:(int(r['logical_batch']),int(r['candidate_index_in_batch'])))
current_log_z_by_N={**{n:float(trainer.tb_loss.exact_tb_log_z_by_node_count[n-1]) for n in trainer.resolved_exhaustive_node_counts}, **{n:float(trainer.tb_loss.log_z_by_node_count[n-1]) for n in trainer.resolved_learned_node_counts}}
health=build_log_z_initialization_health(trajectory_rows,training_rows,node_counts=trainer.resolved_feasible_node_counts,learned_node_counts=trainer.resolved_learned_node_counts,initial_log_z_by_N=initial_log_z_by_N,current_log_z_by_N=current_log_z_by_N,config=health_config)
health_rows=[]
for n,item in health.per_N.items():
    phases=item['tb_delta_by_phase']; health_rows.append({'N':n,'kind':item['normalizer_kind'],'status':item['status'],'valid_trajectories':item['valid_trajectory_count'],'successful_gradient_exposures':item['successful_gradient_exposure_count'],'initial_delta_mean':phases['initialization_pre_update']['mean'],'initial_delta_std':phases['initialization_pre_update']['std'],'early_delta_mean':phases['early']['mean'],'early_delta_std':phases['early']['std'],'late_delta_mean':phases['late']['mean'],'late_delta_std':phases['late']['std'],'initial_log_z':item['initial_log_z'],'current_log_z':item['current_log_z'],'net_change_log_z':item['net_change_log_z'],'directional_update_fraction':item['directional_log_z_update_fraction']})
health_frame=pd.DataFrame(health_rows).set_index('N'); display(health_frame)
health_frame.to_csv(RUN_ROOT/'final_health_by_N.csv'); pd.DataFrame(health.enriched_trajectory_rows).to_csv(RUN_ROOT/'trajectory_tb_health_phases.csv',index=False)
training_frame=pd.json_normalize(training_rows); training_frame.to_csv(RUN_ROOT/'training_health.csv',index=False)
display(training_frame[['logical_batch','optimizer_step','loss','tb_delta_rms','model_gradient_norm_before_clip','model_gradient_clip_coefficient','model_parameter_update_norm','policy_entropy_mean','batch_wall_seconds','cuda_peak_memory_bytes']])
successful=[r for r in training_rows if r['successful_optimizer_update']]
nonfinite=sum(not math.isfinite(float(r[k])) for r in successful for k in ('loss','tb_delta_rms','model_gradient_norm_before_clip','model_parameter_update_norm','policy_entropy_mean'))
counters={'requested_count_by_N':dict(trainer.requested_count_by_N),'valid_count_by_N':dict(trainer.valid_count_by_N),'sampled_attempt_count_by_N':dict(trainer.sampled_attempt_count_by_N),'retry_exhausted_count_by_N':dict(trainer.retry_exhausted_count_by_N),'successful_update_count_by_N':dict(trainer.successful_update_count_by_N)}
evidence_status='insufficient_evidence' if health.insufficient_evidence_node_counts else ('review_required' if health.targeted_recalibration_node_counts or nonfinite else 'candidate_pass')
report={'schema':'factor_gfn.final_no_anchor_health_confirmation.v1','evidence_status':evidence_status,'final_stage5_decision':'manual_review_required','all_learned_initializations_usable':health.all_learned_initializations_usable,'review_node_counts':health.targeted_recalibration_node_counts,'insufficient_evidence_node_counts':health.insufficient_evidence_node_counts,'initialization_health_by_N':health.per_N,'initial_log_z_by_N':initial_log_z_by_N,'current_log_z_by_N':current_log_z_by_N,'logical_batches':len(training_rows),'successful_updates':len(successful),'skipped_updates':len(training_rows)-len(successful),'skip_rate':(len(training_rows)-len(successful))/len(training_rows),'nonfinite_health_values':nonfinite,'policy_gradient_clip_fraction':float(np.mean([r['model_gradient_clip_coefficient']<1.0 for r in successful])),'policy_gradient_clip_coefficient_median':float(np.median([r['model_gradient_clip_coefficient'] for r in successful])),'model_parameter_update_norm_median':float(np.median([r['model_parameter_update_norm'] for r in successful])),'tb_rms_first4_mean':float(np.mean([r['tb_delta_rms'] for r in successful[:4]])),'tb_rms_last4_mean':float(np.mean([r['tb_delta_rms'] for r in successful[-4:]])),'cuda_peak_memory_bytes':int(torch.cuda.max_memory_allocated(device)),**counters}
(RUN_ROOT/'final_health_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print('[health]',{k:report[k] for k in ('evidence_status','review_node_counts','insufficient_evidence_node_counts','logical_batches','successful_updates','skipped_updates','skip_rate','nonfinite_health_values','tb_rms_first4_mean','tb_rms_last4_mean')},flush=True)
print('[health] 该状态只供人工确认；不会自动进入Stage 5。',flush=True)

,kind,status,valid_trajectories,successful_gradient_exposures,initial_delta_mean,initial_delta_std,early_delta_mean,early_delta_std,late_delta_mean,late_delta_std,initial_log_z,current_log_z,net_change_log_z,directional_update_fraction
N,,,,,,,,,,,,,,
1,exact_fixed,fixed_exact_diagnostic,13,13,0.295095,0.0,0.321040,0.016721,0.303028,0.020341,-1.766961,-1.766961,0.000000,NaN
2,exact_fixed,fixed_exact_diagnostic,12,12,1.146679,0.0,0.764726,1.131562,0.858784,1.509528,2.849463,2.849463,0.000000,NaN
3,learned,usable,12,12,-0.021956,0.0,0.365982,0.432264,0.376396,1.644252,5.751882,5.707985,-0.043897,0.916667
4,learned,usable,13,13,0.911178,0.0,0.591171,0.701125,0.698202,0.771544,8.557557,8.528000,-0.029557,0.916667
5,learned,usable,13,13,0.868243,0.0,0.083016,1.984513,-3.171836,4.410684,12.044566,12.025394,-0.019172,0.692308
6,learned,usable,13,13,2.350506,0.0,1.492713,2.452398,1.250786,0.609455,15.843430,15.812887,-0.030542,0.692308
7,learned,usable,12,12,-3.368806,0.0,0.407047,2.091194,3.727066,1.708660,19.031773,19.041296,0.009523,0.666667
8,learned,usable,13,13,1.728363,0.0,0.664007,1.239730,-1.262508,3.091465,23.181034,23.170433,-0.010601,0.538462
9,learned,usable,13,13,-4.657044,0.0,0.276570,0.293050,-0.431921,3.173614,26.251713,26.264919,0.013206,0.700000
10,learned,usable,13,13,3.662332,0.0,-3.225396,1.754901,-0.439873,1.377435,28.327459,28.340174,0.012714,0.916667
11,learned,usable,12,12,-2.798107,0.0,-1.614238,1.486148,-0.172306,2.619199,31.939541,31.968725,0.029184,0.583333
12,learned,usable,11,11,2.124714,0.0,0.435679,3.803741,-1.652763,4.805616,34.499386,34.491264,-0.008121,0.636364
13,learned,usable,12,12,-9.284010,0.0,-5.935819,1.413437,-2.032880,3.415337,36.049942,36.119354,0.069412,1.000000
14,learned,usable,12,12,-4.614304,0.0,-0.724260,4.936919,0.619145,1.282897,39.080486,39.083939,0.003452,0.666667
15,learned,usable,13,13,-2.968191,0.0,-1.201299,3.803559,7.394425,2.727669,43.890156,43.883595,-0.006561,0.615385
16,learned,usable,13,13,0.325979,0.0,6.191814,3.568976,6.494492,6.405474,47.872578,47.807457,-0.065121,1.000000
17,learned,usable,12,12,-7.753500,0.0,7.178439,2.645706,-1.789335,3.326752,46.301888,46.304436,0.002548,0.600000
18,learned,usable,11,11,-0.725934,0.0,4.441426,0.792253,-2.839538,5.162536,46.427258,46.410236,-0.017021,0.600000
19,learned,usable,13,13,-0.459557,0.0,-7.007974,6.622411,-11.333735,0.858308,46.542362,46.581688,0.039326,0.769231
20,learned,usable,12,12,1.364442,0.0,3.484046,4.545924,-12.365177,3.441918,53.216030,53.203079,-0.012951,0.500000

,logical_batch,optimizer_step,loss,tb_delta_rms,model_gradient_norm_before_clip,model_gradient_clip_coefficient,model_parameter_update_norm,policy_entropy_mean,batch_wall_seconds,cuda_peak_memory_bytes
0,1,1,6.496564,2.548836,114.573688,0.043640,0.096706,4.015339,75.750782,137513984
1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,62.239683,137513984
2,3,2,5.932804,2.435735,107.529741,0.046499,0.072115,3.713206,34.589674,137513984
3,4,3,43.678029,6.608936,407.511428,0.012270,0.056076,4.175977,55.432197,137513984
4,5,4,34.191143,5.847319,290.319180,0.017222,0.048989,3.929970,53.701521,137890816
5,6,5,9.499501,3.082126,133.573110,0.037433,0.045401,3.894282,35.335452,137890816
6,7,6,19.187000,4.380297,248.963187,0.020083,0.041589,4.058375,117.407438,169212928
7,8,7,4.553615,2.133920,107.357882,0.046573,0.035641,4.048126,32.654759,169212928
8,9,8,13.081763,3.616872,181.720397,0.027515,0.033447,3.898911,42.834183,169212928
9,10,9,16.152029,4.018959,243.837866,0.020505,0.031817,3.989934,62.198977,169212928
10,11,10,17.774271,4.215954,181.876669,0.027491,0.030721,4.087204,36.069566,169212928
11,12,11,47.832496,6.916104,383.242121,0.013047,0.031414,3.907287,49.572205,169212928
12,13,12,9.743655,3.121483,184.103193,0.027159,0.029262,3.938021,93.302892,169212928
13,14,13,6.313959,2.512759,68.363762,0.073138,0.028693,3.801873,22.379750,169212928
14,15,14,48.292438,6.949276,364.497075,0.013718,0.026123,3.965358,61.975460,169212928
15,16,15,42.152028,6.492459,409.859361,0.012199,0.027489,4.016690,78.250222,169212928
16,17,16,29.713316,5.450992,305.430967,0.016370,0.027591,3.946914,73.180940,169212928
17,18,17,38.252746,6.184880,291.564632,0.017149,0.026364,3.674650,37.565805,169212928
18,19,18,14.205956,3.769079,166.694145,0.029995,0.027854,3.830258,58.755423,169212928
19,20,19,57.417256,7.577417,373.771673,0.013377,0.027304,3.840062,61.549053,169212928
20,21,20,42.018753,6.482187,336.811514,0.014845,0.027273,4.057216,40.319322,169212928
21,22,21,25.317182,5.031618,353.502916,0.014144,0.027770,3.942413,90.959273,169212928
22,23,22,5.083030,2.254558,81.447515,0.061389,0.028179,3.748642,44.358111,169212928
23,24,23,31.355584,5.599606,338.169720,0.014785,0.026164,4.039181,91.468961,169212928
24,25,24,78.030874,8.833509,495.612101,0.010089,0.025213,4.088782,40.716331,169212928
25,26,25,40.113800,6.333546,290.677597,0.017201,0.024272,3.891282,41.326084,169212928
26,27,26,49.697066,7.049615,502.500113,0.009950,0.025970,4.313947,71.427578,169212928
27,28,27,24.146462,4.913905,255.990604,0.019532,0.023421,3.576265,59.805776,169212928
28,29,28,21.627801,4.650570,276.732687,0.018068,0.022972,4.354872,87.250133,169212928
29,30,29,18.518628,4.303328,242.914856,0.020583,0.022149,4.075540,61.108734,169212928
30,31,30,8.823265,2.970398,104.125780,0.048019,0.022540,3.928874,15.568280,169212928
31,32,31,44.791085,6.692614,375.648572,0.013310,0.020723,3.953449,59.901866,169212928

[health] {'evidence_status': 'candidate_pass', 'review_node_counts': (), 'insufficient_evidence_node_counts': (), 'logical_batches': 32, 'successful_updates': 31, 'skipped_updates': 1, 'skip_rate': 0.03125, 'nonfinite_health_values': 0, 'tb_rms_first4_mean': 4.360206343341333, 'tb_rms_last4_mean': 4.654227424741547}
[health] 该状态只供人工确认；不会自动进入Stage 5。

### 第 4 格：验证 checkpoint 确定性恢复

最后保存冻结的32-batch状态，然后从同一 checkpoint 分别执行 source/resume 各一个 batch，逐值比较目标N、轨迹、loss、logZ、scheduler和模型。两个真实batch通常约2–4分钟，各自每20秒 heartbeat；它们只用于确定性验证，不写入前面的32-batch健康审计。

In [6]:
checkpoint=RUN_ROOT/'checkpoint_before_determinism.pt'; trainer.save_checkpoint(checkpoint)
print('[determinism] source batch starting; heartbeat every20s',flush=True)
with provider.phase('determinism_source'):
    with progress_heartbeat('final health determinism source',interval_seconds=20.0): expected=trainer.train_step()
expected_diag=trainer.last_discovery_trajectory_diagnostics; expected_model={k:v.detach().clone() for k,v in trainer.model.state_dict().items()}; expected_log_z=trainer.tb_loss.log_z_by_node_count.detach().clone(); expected_scheduler=trainer.complexity_scheduler.state_dict()
resumed=GFNTrainer(config,provider,device=device); configure_registry_once(resumed,registry); resumed.load_checkpoint(checkpoint)
print('[determinism] resume batch starting; heartbeat every20s',flush=True)
with provider.phase('determinism_resume'):
    with progress_heartbeat('final health determinism resume',interval_seconds=20.0): actual=resumed.train_step()
assert actual==expected and resumed.last_discovery_trajectory_diagnostics==expected_diag
assert resumed.complexity_scheduler.state_dict()==expected_scheduler and torch.equal(resumed.tb_loss.log_z_by_node_count,expected_log_z)
assert all(torch.equal(resumed.model.state_dict()[k],v) for k,v in expected_model.items())
report['checkpoint_resume_exact']=True; (RUN_ROOT/'final_health_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
registry.close()
print('FINAL_NO_ANCHOR_HEALTH_CONFIRMATION_COMPLETE',flush=True)
print('把结果目录交给Codex分析：',RUN_ROOT,flush=True)

[determinism] source batch starting; heartbeat every20s
[final health determinism source] still running; elapsed=20.0s
[final health determinism source] still running; elapsed=40.1s
[registry-proof] verified_once={1: 6, 2: 636}
[determinism] resume batch starting; heartbeat every20s
[final health determinism resume] still running; elapsed=20.0s
FINAL_NO_ANCHOR_HEALTH_CONFIRMATION_COMPLETE
把结果目录交给Codex分析： D:\实习\Gflownet因子挖掘\runs\final_health_confirmation_6_20\final_health_seed42